name: Nexus CLI (3 nodes, persist state)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

permissions:
  contents: read
  actions: read

env:
  NODE_IDS: "35903257 35928252 35930731"

jobs:
  nexus:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download previous state artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: main.yml
          name: nexus-state
          path: /tmp/nexus-state
          if_no_artifact_found: ignore

      - name: Restore state (if present)
        run: |
          set -euxo pipefail
          sudo mkdir -p /opt/state
          sudo chown -R "$USER:$USER" /opt/state
          if [ -f /tmp/nexus-state/home-runner-nexus.tar.gz ]; then
            tar -xzf /tmp/nexus-state/home-runner-nexus.tar.gz -C "$HOME"
          fi
          if [ -f /tmp/nexus-state/opt-state.tar.gz ]; then
            sudo tar -xzf /tmp/nexus-state/opt-state.tar.gz -C /
            sudo chown -R "$USER:$USER" /opt/state
          fi
          mkdir -p /opt/state/logs

      - name: Prepare system
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y tmux curl

      - name: Install Nexus CLI
        run: |
          set -euxo pipefail
          curl https://cli.nexus.xyz/ | sh
          echo "$HOME/.nexus/bin" >> "$GITHUB_PATH"

      - name: Verify nexus-network path
        id: which
        run: |
          set -euxo pipefail
          if ! command -v nexus-network >/dev/null 2>&1; then
            NEXUS_BIN=$(find "$HOME" -type f -name nexus-network 2>/dev/null | head -n1 || true)
            if [ -n "$NEXUS_BIN" ]; then
              echo "fallback=$NEXUS_BIN" >> $GITHUB_OUTPUT
            else
              echo "Không tìm thấy nexus-network sau khi cài đặt." >&2
              exit 1
            fi
          else
            echo "fallback=" >> $GITHUB_OUTPUT
          fi

      - name: Ensure start script exists
        run: |
          set -euxo pipefail
          if [ ! -f /opt/state/start-nexus.sh ]; then
            cat > /opt/state/start-nexus.sh <<'EOF'
            #!/usr/bin/env bash
            set -euo pipefail

            NODE_ID="$1"
            LOG_DIR="/opt/state/logs"
            mkdir -p "$LOG_DIR"

            bash -lc "
              command -v nexus-network && nexus-network --version || true
              while true; do
                echo \"[$(date -Is)] starting node $NODE_ID\"
                nexus-network start --node-id \"$NODE_ID\" 2>&1 | tee -a \"$LOG_DIR/node$NODE_ID.log\"
                echo \"[$(date -Is)] node $NODE_ID exited, restart in 15s...\"
                sleep 15
              done
            "
            EOF
            chmod +x /opt/state/start-nexus.sh
          fi

      - name: Start 3 Nexus nodes in tmux
        run: |
          set -euxo pipefail
          if [ -n "${{ steps.which.outputs.fallback }}" ]; then
            export PATH="$(dirname "${{ steps.which.outputs.fallback }}"):$PATH"
          fi
          for ID in $NODE_IDS; do
            tmux has-session -t "node${ID}" 2>/dev/null && tmux kill-session -t "node${ID}" || true
          done
          for ID in $NODE_IDS; do
            tmux new-session -d -s "node${ID}" "/opt/state/start-nexus.sh ${ID}"
          done
          tmux ls || true

      - name: Open tmate (manual only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: Let it run
        run: |
          sleep $((5*60*60 + 50*60))

      - name: Create state archives
        run: |
          set -euxo pipefail
          mkdir -p /tmp/state-bundle
          tar -czf /tmp/state-bundle/home-runner-nexus.tar.gz -C "$HOME" .nexus || true
          sudo tar -czf /tmp/state-bundle/opt-state.tar.gz -C / opt/state
          sudo chown "$USER:$USER" /tmp/state-bundle/*.tar.gz

      - name: Upload state artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexus-state
          path: /tmp/state-bundle
          retention-days: 14
